version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./env/app/Dockerfile
    volumes:
      - ./app:/app
  app-debug:
    build:
      context: .
      dockerfile: ./env/app-debug/Dockerfile
    volumes:
      - ./app:/app
      - ./env/app-debug/php.ini-development:/usr/local/etc/php/php.ini
  mysql:
    image: mysql:8.0.18
    volumes:
      - ./env/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password

#  elasticsearch:
#    build:
#      context: ./env/elasticsearch
#      dockerfile: ./Dockerfile
#    ports:
#      - 9200:9200

#  logstash:
#    build:
#      context: .
#      dockerfile: ./env/logstash/Dockerfile

  fluentd:
    build:
      context: ./env/fluentd
      dockerfile: ./Dockerfile
    volumes:
      - ./env/fluentd/fluent.template.conf:/fluentd/etc/fluent.template.conf
    ports:
      - '8888:8888'
      - '24220:24220'
    environment:
      - DOLLAR=$$
    depends_on:
      - mysql
      - elasticsearch

#  kibana:
#    build:
#      context: ./env/kibana
#      dockerfile: ./Dockerfile
#    ports:
#      - '5601:5601'
#    depends_on:
#      - elasticsearch
#    environment:
#      - "ELASTICSEARCH_URL=http://elasticsearch:9200"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    ports:
      - 9200:9200
    networks: [elastic]
    environment:
      - discovery.type=single-node

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.4.2
    ports:
      - 5601:5601
    networks: [elastic]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    ports:
      - '8080:80'
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - PMA_HOST=mysql

networks:
  elastic: