version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./env/app/Dockerfile
    volumes:
      - ./app:/app
  app-debug:
    build:
      context: .
      dockerfile: ./env/app-debug/Dockerfile
    volumes:
      - ./app:/app
      - ./env/app-debug/php.ini-development:/usr/local/etc/php/php.ini
  mysql:
    image: mysql:8.0.18
    volumes:
      - ./env/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password
  elasticsearch:
    image: elasticsearch:7.4.2
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    ports:
      - '8080:80'
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - PMA_HOST=mysql
